### ISSUE TITLE
Integrate with appveyor

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#129]
So we have something to hit the Windows guys with when they have random issues.

I think angular2 seed are integrated so should be easy enough.

**Comment by lathonez** [comment]
started this finally for #194 npm test is running

**Comment by lathonez** [comment]
basically working, need e2e

**Comment by lathonez** [comment]
Had a quick go at e2e, initial blocker is that `ionic:build` fails on jasmine types missing.

here is the yml:

```yml
# Test against this version of Node.js
environment:
  nodejs_version: "6.5"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g cordova ionic angular-cli
  - ionic state clear
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - ng test --watch=false

build: off

deploy:
- provider: Local
  AppVeyor-Protractor-test-app.deploy_website: true
  AppVeyor-Protractor-test-app.site_name: Test
  AppVeyor-Protractor-test-app.hostname: localhost
  AppVeyor-Protractor-test-app.port: 47602
  AppVeyor-Protractor-test-app.protocol: http
  AppVeyor-Protractor-test-app.remove_files: true

before_deploy:
  - npm run ionic:build

after_deploy:
  - npm run e2e
```

based on this: https://github.com/FeodorFitsner/AppVeyor-Protractor-test-app/blob/master/appveyor.yml
